title: Anthony Lomeli
description: "Musing of a guy that just wants to code"
author:
  name: "Lomeli"
  email: "anthony@lomeli12.net"
  url: "https://lomeli12.net"

baseurl: 

source: .
destination: ./_site
permalink: /post/:title
paginate: 5
paginate_path: "/blog/page:num/"

google_analytics: "UA-42257695-1"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "lomeli"
year : "2020"
